Update docs for v2
go-generalize/api_gen pull request #173
Opened 2021-04-15 12:44 UTC by cs3238-tsuzu

2021-04-15 12:53 UTC, 54m requested changes

2021-04-15 12:53 UTC, 54m commented on docs/server_ja.md
> +- apiフォルダか　らのフォルダのパスがURLのパスとなる。
```suggestion
- apiフォルダからのフォルダのパスがURLのパスとなる。
```

2021-04-15 13:25 UTC, cs3238-tsuzu commented on docs/server_ja.md
> +- apiフォルダか　らのフォルダのパスがURLのパスとなる。
ありがとう

2021-04-25 18:09 UTC, 54m requested changes

2021-04-25 18:09 UTC, 54m commented on docs/server_ja.md
> +#### api_genで利用するフォルダを作成する
```suggestion
#### api_genで利用するディレクトリを作成する
```
名称の統一

2021-04-25 18:09 UTC, 54m commented on docs/server_ja.md
> +#### API定義を書くフォルダを用意する
```suggestion
#### API定義を書くディレクトリを用意する
```
名称の統一

2021-04-25 18:09 UTC, 54m commented on docs/server_ja.md
> +- apiフォルダからのフォルダのパスがURLのパスとなる。
```suggestion
- apiディレクトリからのディレクトリのパスがURLのパスとなる。
```
名称の統一

2021-04-25 18:09 UTC, 54m commented on docs/server_ja.md
> +$ cd ../ # api_genフォルダ
```suggestion
$ cd ../ # api_genディレクトリ
```
名称の統一

2021-04-25 18:09 UTC, 54m commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
`juhubujua` これ何？w

2021-04-28 17:32 UTC, cs3238-tsuzu commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
何これw

2021-04-28 17:33 UTC, 54m commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
www
![知りませんw](https://user-images.githubusercontent.com/30588003/116447758-49fe6600-a893-11eb-96e0-f78bc24de7d6.jpeg)

2021-04-28 17:33 UTC, cs3238-tsuzu commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
直しました 🙇

2021-04-28 17:35 UTC, moezakura commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
Google翻訳が汚染されてた可能性

2021-04-28 17:37 UTC, 54m commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
@cs3238-tsuzu 
まだ残ってるよ！Push出来てる？

2021-04-29 05:31 UTC, cs3238-tsuzu commented on docs/server_en.md
> +#### Create juhubujua directory for API definitions
fetch/rebaseしてなかった〜〜〜pushしました

2021-04-29 05:32 UTC, 54m approved these changes
LGTM

2021-04-29 05:33 UTC, merged