Add E2E test for multipart in TypeScript
go-generalize/api_gen pull request #295
Opened 2022-03-18 14:21 UTC by tsuzu

2022-03-28 12:29 UTC, 54m requested changes
e2eについてのドキュメント残して欲しいです！
例えば、api_genに新しい機能を追加したはいいけど具体的にどこに記述していいかわからない（そもそも知らずにテスト書かない）などないようにしたい為

2022-03-28 12:29 UTC, 54m commented on e2e/e2eutil/file.go
> +	b, err := ioutil.ReadFile(path)
```suggestion
	"os"
	"testing"
)

// RunCommand loads a file from the given path.
func ReadFile(t *testing.T, path string) string {
	t.Helper()

	b, err := os.ReadFile(path)
```

2022-03-29 05:16 UTC, tsuzu commented
追加しました

2022-03-29 06:24 UTC, 54m approved these changes
LGTM

2022-03-29 06:24 UTC, merged